- name: Set up locale
  locale_gen: name={{ default_locale }} state=present

- name: Set up locale (LC_ALL)
  lineinfile: dest=/etc/default/locale
    regexp="LC_ALL"
    line="LC_ALL=\"{{ default_locale}}\""

- name: Install system packages
  apt: name={{ item }} update_cache=yes state=installed
  with_items:
    - build-essential
    - libstdc++6
    - python-virtualenv
    - python3-dev
    - python3-pip
    - git
    - supervisor

- name: Install extra packages
  apt: name={{ item }} update_cache=yes state=installed
  with_items:
    - libtiff5-dev
    - libjpeg8-dev
    - zlib1g-dev
    - libfreetype6-dev
    - liblcms2-dev
    - libwebp-dev

- pip: name=setuptools

- name: Create the SSH public key file
  copy: src={{ ssh_private_key }}.pub
        dest=/root/.ssh/id_rsa.pub
        mode=0644
  when: ssh_github is defined

- name: Create the SSH private key file
  copy: src={{ ssh_private_key }}
        dest=/root/.ssh/id_rsa
        mode=0600
  when: ssh_github is defined and is_private_repo is defined
