# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-15 22:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255)),
                ('district', models.CharField(max_length=100)),
                ('image_url', models.ImageField(upload_to='')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='core.City')),
            ],
            options={
                'verbose_name': 'Denúncias',
                'verbose_name_plural': 'Denúncias',
            },
        ),
    ]
