# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-15 23:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='report',
            name='description',
            field=models.TextField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='report',
            name='landmark',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='report',
            name='latitude',
            field=models.FloatField(blank=True, default='0.00'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='report',
            name='longitude',
            field=models.FloatField(blank=True, default='0.00'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='report',
            name='modified_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='report',
            name='status',
            field=models.IntegerField(choices=[(1, 'Enviada'), (2, 'Em análise'), (3, 'Foco Tratado'), (4, 'Foco não encontrado')], default=1),
        ),
    ]
