# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-25 13:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_auto_20160906_1116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='reason',
            field=models.TextField(verbose_name='Razão do Status'),
        ),
    ]
