# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-25 13:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_auto_20161025_1341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='reason',
            field=models.TextField(blank=True, verbose_name='Razão do Status'),
        ),
    ]
