# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-26 09:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0012_auto_20161026_0947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='reason',
            field=models.TextField(blank=True, null=True, verbose_name='Razão do Status'),
        ),
    ]
