# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-31 06:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0013_auto_20161026_0948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='status',
            field=models.IntegerField(choices=[(0, 'Não Enviada'), (1, 'Enviada'), (2, 'Em análise'), (3, 'Foco tratado'), (4, 'Foco não encontrado'), (5, 'Transferida')], default=0, verbose_name='Status'),
        ),
    ]
