# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-02 20:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0014_auto_20161031_0648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='image_url',
            field=models.ImageField(blank=True, null=True, upload_to='denuncias/'),
        ),
    ]
