- name: Set up a production machine
  hosts: production
  become: yes
  become_user: root
  remote_user: root
  vars_files:
    - env_vars/base.yml
    - env_vars/production.yml
  roles:
    - common
    - mysql
    - project
    - gunicorn
    - supervisor
    - nginx
    - certbot