- name: Create project with vagrant
  hosts: all
  become: yes
  become_user: root
  remote_user: vagrant
  vars_files:
    - env_vars/base.yml
    - env_vars/development.yml
  roles:
    - {role: swap, when: create_swap_file}
    - common
    - mysql
    - project
    - gunicorn
    - supervisor
    - nginx