# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-16 15:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='state',
            field=models.CharField(choices=[('AL', 'Alagoas'), ('AP', 'Amapá'), ('MG', 'Minas Gerais'), ('AM', 'Amazonas'), ('PA', 'Pará'), ('SC', 'Santa Catarina'), ('MT', 'Mato Grosso'), ('SP', 'São Paulo'), ('RN', 'Rio Grande do Norte'), ('RJ', 'Rio de Janeiro'), ('BA', 'Bahia'), ('MA', 'Maranhão'), ('GO', 'Goiás'), ('TO', 'Tocantins'), ('PI', 'Piauí'), ('PB', 'Paraíba'), ('MS', 'Mato Grosso do Sul'), ('SE', 'Sergipe'), ('RR', 'Roraima'), ('ES', 'Espírito Santo'), ('AC', 'Acre'), ('PE', 'Pernambuco'), ('PR', 'Paraná'), ('CE', 'Ceará'), ('RO', 'Rondônia'), ('RS', 'Rio Grande do Sul'), ('DF', 'Distrito Federal')], max_length=2),
        ),
    ]
